name: App Build Test (Docs)
on:
  push:
    branches:
      - "actions/app__build-test__docs__*"
  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/app__build-test__docs.yml"
      - ".github/checkgroup.yml"
      - "scripts/bash/initialize_environment.sh"
      - "scripts/configure_flutter.sh"
      - "app/**"
  schedule:
    - cron: 0 2 * * *
jobs:
  app__build-test__docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: configure Flutter
        working-directory: ./scripts/bash
        run: source ./initialize_environment.sh && ./configure_flutter.sh
      - name: build docs
        working-directory: ./scripts/bash
        run: source ./initialize_environment.sh && ./build_app_docs.sh
