name: checkin iwfpapi
on:
  push:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
      - "refactor/*"
      - "fix/*"
    paths:
      - "iwfpapi/**"
      - ".github/workflows/checkin_iwfpapi.yml"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: 0 2 * * *
jobs:
  unit-test:
    name: run iwfpapi checkin tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      - name: install firebase cli for non-windows
        if: matrix.os != 'windows-latest'
        run: sudo curl -sL firebase.tools | bash
      - name: install firebase cli for windows
        if: matrix.os == 'windows-latest'
        run: npm install -g firebase-tools
      - name: install iwfpapi dependencies
        run: |
          cd ./iwfpapi/functions
          npm install
      - name: lint iwfpapi typescript code
        run: |
          cd ./iwfpapi/functions
          npm run lint
      - name: run iwfpapi unit tests
        run: |
          cd ./iwfpapi/functions
          npm run e2e
