name: Deploy

on:
  push:
    branches:
      - "master"
      - "actions/*"
    paths:
      - "iwfpapp/**"
      - ".github/**"

jobs:
  deploy-web:
    name: Deploy Web app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.4'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: enable flutter web config
        run: flutter config --enable-web
      - name: build for web
        run: |
          cd ./iwfpapp
          flutter build web
      - name: install firebase cli
        run: sudo npm install -g firebase-tools
      - name: deploy to firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
      - name: upload web artifects
        uses: actions/upload-artifact@master
        with:
          name: web-app
          path: iwfpapp/build/web
  deploy-android:
    name: Deploy Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.4'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: build apk package
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
        run: |
          cd ..
          git clone https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/tianhaoz95/${{ secrets.SECRET_REPO }}.git
          cp ./${{ secrets.SECRET_REPO }}/iwfp/key.jks ./iwfp/iwfpapp/android/app
          cd ./iwfp
          export PROJ=$HOME
          ./scripts/setenv.sh
          cd ./iwfpapp
          flutter build apk --split-per-abi
          flutter build appbundle
      - name: upload apk artifects
        uses: actions/upload-artifact@master
        with:
          name: android-apk
          path: iwfpapp/build/app/outputs/apk
      - name: upload app bundle artifects
        uses: actions/upload-artifact@master
        with:
          name: android-app-bundle
          path: iwfpapp/build/app/outputs/bundle
  deploy-ios:
    name: Deploy IOS app
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.4'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: build iOS package
        run: |
          cd ./iwfpapp
          flutter build ios --release --no-codesign
      - name: upload artifects
        uses: actions/upload-artifact@master
        with:
          name: ios-app
          path: iwfpapp/build/ios/iphoneos
