name: iwfp api checkin
on:
  push:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
    paths:
      - "iwfpapi/**"
      - ".github/**"
  pull_request:
    branches:
      - "master"
      - "dev/*"
      - "feature/*"
      - "release/*"
  schedule:
    - cron: 0 2 * * *
  
jobs:
  unit-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install firebase cli for non-windows
        if: matrix.os != 'windows-latest'
        run: sudo npm install -g firebase-tools
      - name: install firebase cli for windows
        if: matrix.os == 'windows-latest'
        run: npm install -g firebase-tools
      - name: install iwfpapi dependencies
        run: |
          cd ./iwfpapi/functions
          npm install
      - name: install iwfpapi dependencies
        run: |
          cd ./iwfpapi/functions
          npm install
      - name: lint iwfpapi typescript code
        run: |
          cd ./iwfpapi/functions
          npm run lint
      - name: run iwfpapi unit tests
        run: |
          cd ./iwfpapi/functions
          npm test
