name: release Android app
on:
  push:
    branches:
      - "master"
      - "actions/release-android-app__*"
    paths:
      - "app/pubspec.yaml"
      - "app/android/fastlane/Fastfile"
      - ".github/workflows/release_android_app.yml"
jobs:
  release-android-app:
    name: release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.9'
          channel: 'stable'
      - name: install bundler
        run: gem install bundler:1.17.3
      - name: install ruby packages
        working-directory: ./app/android
        run: bundle install
      - name: prepare credentials
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: ./scripts/setenv.sh
      - name: install dependencies
        working-directory: ./app
        run: flutter pub get
      - name: build apk
        working-directory: ./app
        run: flutter build apk --split-per-abi
      - name: build app bundle
        working-directory: ./app
        run: flutter build appbundle
      - name: publish to internal track
        working-directory: ./app/android
        run: bundle exec fastlane internal
