name: Release Server Emulator Image
on:
  pull_request:
    branches:
      - master
    paths:
      - "environments/chromedriver/**"
      - ".github/workflows/release__environment__chrome-driver.yml"
  push:
    branches:
      - master
    paths:
      - "environments/chromedriver/**"
      - ".github/workflows/release__environment__chrome-driver.yml"
  schedule:
    - cron: 0 2 * * *
jobs:
  release__environment__chrome-driver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.2"
      - run: npm install
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: get_tag
        id: get_tag
        working-directory: scripts
        env:
          USERNAME: ${{ github.repository_owner }}
        run: |
          source query_image_tag.sh
          echo "::set-output name=image_tag::ghcr.io/$USERNAME/iwfp-chrome-driver:$USE_TAG_NAME"
      - uses: docker/build-push-action@v2
        with:
          context: ./environments/chromedriver
          file: ./environments/chromedriver/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.get_tag.outputs.image_tag }}
