name: release firebase
on:
  push:
    branches: 
      - "master"
      - "actions/release-firebase__*"
      - "actions/server-refactor__*"
    paths:
      - "site/*"
      - "functions/*"
      - "app/*"
      - ".github/workflows/release_firebase.yml"
jobs:
  release-firebase:
    name: release Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.9'
          channel: 'stable'
      - name: install firebase cli
        run: npm install -g firebase-tools
      - name: install yarn
        run: npm install -g yarn
      - name: install coverage visualization tools
        run: sudo apt install -y lcov
      - name: switch to master channel
        run: flutter channel master
      - name: enable Flutter web
        run: flutter config --enable-web
      - name: verify Flutter version
        run: flutter --version
      - name: install app dependencies
        working-directory: ./app
        run: flutter pub get
      - name: install server dependencies
        working-directory: ./functions
        run: npm install
      - name: install site dependencies
        working-directory: ./site
        run: yarn install
      - name: test app with coverage
        working-directory: ./app
        run: flutter test --coverage
      - name: generate app coverage report
        working-directory: ./app
        run: genhtml coverage/lcov.info -o coverage
      - name: build web app
        working-directory: ./app
        run: flutter build web
      - name: build app docs
        working-directory: ./app
        run: FLUTTER_ROOT=. $FLUTTER_HOME/bin/cache/dart-sdk/bin/dartdoc --exclude 'dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart:ui,dart:ffi,dart:html,dart:js,dart:js_util'
      - name: build server docs
        working-directory: ./functions
        run: npm run docs
      - name: build project site
        working-directory: ./site
        run: yarn docs:build
      - name: deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
        run: firebase deploy --token $FIREBASE_TOKEN
        
