name: Release Android App
on:
  pull_request:
    branches:
      - "master"
    paths:
      - ".github/checkgroup.yml"
      - ".github/workflows/release__android-app.yml"
      - "scripts/bash/configure_flutter.sh"
      - "scripts/bash/configure_ruby.sh"
      - "scripts/bash/initialize_environment.sh"
      - "scripts/bash/app/release/android.sh"
      - "scripts/bash/app/build/android.sh"
  push:
    branches:
      - "master"
    paths:
      - "app/pubspec.yaml"
      - "app/android/fastlane/Fastfile"
jobs:
  release__android-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Monorepo-Actions/config-for-actions@main
        id: get_action_configs
        with:
          config_files: ./configs/actions.json
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get_action_configs.outputs.flutter_version }}
          channel: ${{ steps.get_action_configs.outputs.flutter_channel }}
      - name: "Configure dependencies, fetch credentials and build Android package"
        working-directory: ./scripts/bash
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          source ./initialize_environment.sh
          ./configure_flutter.sh
          ./configure_ruby.sh
          ./app/cred/fetch_android.sh
          ./app/build/android.sh
      - name: publish to internal track
        if: ${{ github.event_name == 'push' }}
        working-directory: ./scripts/bash
        run: |
          source ./initialize_environment.sh
          ./app/release/android.sh
