name: web release
on:
  push:
    branches:
      - "master"
      - "actions/release-iwfpapp-web__*"
    paths:
      - "iwfpapp/pubspec.yaml"
      - ".github/workflows/release_iwfpapp_web.yml"
      - "Gemfile"
      - "Gemfile.lock"
jobs:
  release-web:
    name: release iwfpapp web app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'
          channel: 'stable'
      - name: upgrade flutter
        run: |
          flutter channel master
          flutter upgrade
      - name: clean up workspace
        run: git clean -xffd
      - name: enable flutter web config
        run: flutter config --enable-web
      - name: build for web
        run: |
          cd ./iwfpapp
          flutter pub get
          flutter test
          flutter build web
      - name: install firebase cli
        run: sudo npm install -g firebase-tools
      - name: deploy to firebase
        run: |
          cd ./iwfpapp
          sudo firebase deploy --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }} --only hosting:iwfp
